### PR TITLE
Import commits

### PR DESCRIPTION
**Pull request by xcoulon**

### CODE REVIEW

**Comment by xcoulon** [comment]
@aslakknutsen @kwk @alexeykazakov @surajssd @sbose78 @corinnekrych @nurali-techie:
I just added you as reviewers for this PR. I'm not asking you to review all the code here, but rather this is to show that it's possible to retrieve all commits for a subset of `fabric8-wit` and import them in a single pull request. Those commits were exported as a series of patch (basically, 1 per pkg) and then applied on the local repository, on a topic branch.
Once applied, we should have more or less what we have in https://github.com/fabric8-services/fabric8-common.old, but with the commit history, as @kwk and @alexeykazakov recently requested in a PR review.
Please let me know if you're OK with proceeding with the merge (not squashed!)

**Comment by corinnekrych** [comment]
@xcoulon interesting that you even put the git command into `Makefile`. it could be useful even longer term as the essence of common is to unify good practices in different repo. i think i'll redo this PR https://github.com/fabric8-services/fabric8-common.old/pull/6 taking the original https://github.com/fabric8-services/fabric8-toggles-service/blob/master/Dockerfile but therefore I could not use your target as it's only go specific.

**Comment by xcoulon** [comment]
@corinnekrych I think that the `import` goal should also work with the Dockerfile, it's just that the `sed` command will not do any change in the patch, I believe

**Comment by corinnekrych** [comment]
@xcoulon ahhh, let me try...

**Comment by kwk** [comment]
> Those commits were exported as a series of patch (basically, 1 per pkg) and then applied on the local repository, on a topic branch.

Hi @xcoulon. To me this looks too complicated. Am I right that most of the code in fabric8-common comes from fabric8-wit? If that is the case I would take that (fabric8-wit) as a basis and instead of pulling commit *in* I would throw code *out* with new commits and then add commits to track the cleanup process. What do you think about this process? I thought I did recommend this way, didn't I?

**Pull request merged**
