### PR TITLE
Add initial logging package

### PR DESCRIPTION
**Pull request by stooke**
This adds support for the initial logging package, mostly taken from fabric8-auth.
To make this work, several other packages were imported and trimmed to the minimum.

included are: 
- logging
- configuration
- testutil (renamed from resources)
- errors
- jsonapi
- util

Unit tests exist and pass, and a sample main.go is provided.

Before this is merged, I will support proper configurable environment variables for the config options, etc.

### CODE REVIEW

**Comment by surajssd** [comment]
Can we do small changes, one thing at a time, so that it is easy to test the integration in other repositories? I am not very comfortable with huge code moving like this?

**Comment by surajssd** [comment]
It brings in the problems which are hard to trace later.

**Comment by stooke** [comment]
I sympathize with the sentiment of applying small changes, and for the most part agree, but when I tried to do this with logging, it pulls in a bunch of other common code.  

My belief was that since this code would be added to the common repo soon anyways, I should bite the bullet and get it in now.  Otherwise you end up heavily modifying the code to make it independent, then later on modifying it back to take advantage of the other common features.  This large commit lets me get a build infrastructure going, and also see what other issues we'll encounter (specifically configuration and initialization).

It is true that one could build the common repo up from smaller commits like PR #3, but my task was to start with the logging package, and I've tried to bring in only the minimal amount to get that going and useful.

**Comment by xcoulon** [comment]
closing this PR since those packages were part of https://github.com/fabric8-services/fabric8-common/commit/8a7d576dfc5142f5210d164c7ba6c0181b384402

**Pull request closed without merging**
